version: '3'

services:
    php:
        container_name: back-end-v2.
        build:
            context: ./docker/php/
            dockerfile: ./Dockerfile
        restart: always
        ports:
            - 8000:80
        volumes:
            - ./php/:/var/www/html/
